---
title: "Visualising and Summarizing US National Highway Traffic Safety Administration Fatality Analysis Reporting System Data"
author: "Waldo van der Merwe"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This package allows the seamless visualisation of data from the US National Highway Traffic Safety Administration Fatality Analysis Reporting System. This system can be found on the web [here](https://www.nhtsa.gov/Data/Fatality-Analysis-Reporting-System).

## Exported functions

There are two exported functions:
`fars_map_state()` and `fars_summarize_years()`
The parameters and outputs for both are found withing the help documentation for each. Type:

`?fars_map_state` 
or
`?fars_summarize_years`
to find more details.

## Data

No data is included in this package. Data can be obtained from the above mentioned FARS link. The only criteria is that the data should be in CSV format and compressed bz2 format. The data files must reside in the same working directory as the R script files containing the above functions.  

